# 1조 회고

## 👨‍👩‍👧‍👦 참여 인원: 3명

### 김하영, 이기성, 이지영

## 🎙️ 발표자

### 김하영, 이기성, 이지영

## 👨‍🎤 질의 응답
#### 1. [Symbol.species]
```jsx
class SubArray extends Array {}

const subArray = new SubArray(1, 2, 3).map((e) => e * 2);
console.log(subArray instanceof SubArray); // true
console.log(subArray instanceof Array); // true

class SubArrayOverride extends Array {
  static get [Symbol.species]() { 
    return Array; // (*2*)
  }
}

const subArrayOverride = new SubArrayOverride(1, 2, 3).map((e) => e * 2);
console.log(subArrayOverride instanceof SubArrayOverride); // false (*1*)
console.log(subArrayOverride instanceof Array); // true
출처: https://jake-seo-dev.tistory.com/333 [제이크서 위키 블로그:티스토리]
```
`(*1*)` 표시한 부분이 왜 false인지?
`(*2*)` 부분에서 명시적으로 Array를 지정gka
- 이는 map()드의 메서드가 새 배열을 만들 떄 subArrayOverride 대신 일반 Array를 사용하라는 의미
- 그 결과 map()이 반환하는 새 배열은 일반 Array의 인스턴스가 되어 subArrayOverride의 인스턴스가 아님
즉, 자식이 다른 성을 쓰도록 지정된 경우라서, 생성된 새 배열이 더 이상 subArrayOverride의 인스턴스가 아니라 일반 Array의 인스턴스다.

#### 2. 자바스크립트에서는 protected를 지원하지 않는다고 하는데 어떻게 사용하는가?
- public과 private처럼 명시적으로 자바스크립트에서 지원하는 것이 아니라 개발자들이 임의로 _를 사용해서 protected임을 표시함

## 💡 의견 공유
-  이기성: next에서 에러를 캐치하는 방식에는 try catch도 있지만 
 ```if(error instanceof Error)``` 형태도 있다.

```jsx
const res = await fetch(href, {
    signal: AbortSignal.timeout(7_000),
  }).catch((err) => err as Error)

  if (res instanceof Error) {
    const err = res as Error
    if (err.name === 'TimeoutError') {
      Log.error('upstream image response timed out for', href)
      throw new ImageError(
        504,
        '"url" parameter is valid but upstream response timed out'
      )
    }
    throw err
  }
```

`fetch`의 결과가 `instanceof` 를 통해 `Error` 객체에 속하는지 판별하여 `true`라면 에러를 `throw` 해주는 방식을 사용하고 있다.
## 💡 자료 공유
- 김하영: Symbol.species 심볼과 용례 https://jake-seo-dev.tistory.com/333
